### ISSUE TITLE
Incorrect Top/Bottom Panel perforation calculation

### ISSUE THREAD

**Issue by kuoliangkwong** [neo-cld/Formd-T1-v2-Modeling#3]
Just noticed there're miscalculations on the following:
1. Miscalculation & space inconsistency between perforations. It should be around 1.95mm between the perforation. 
![Incorrect space between perforations](https://user-images.githubusercontent.com/8188634/210046897-049e3715-4623-4dd1-8bbc-23989481640d.png)

2. Miscalculation space between perforations and panel edge. Probably caused by the incorrect space between perforation.
![Incorrect space between perforation and edge](https://user-images.githubusercontent.com/8188634/210047097-b5b84de9-03e3-4a2c-89bb-014836f338d9.png)
It should be like these:
13mm
![IMG_7730](https://user-images.githubusercontent.com/8188634/210047135-82da8b80-4640-45c0-930e-299802e63816.jpg)
12mm
![IMG_7731](https://user-images.githubusercontent.com/8188634/210047149-e1a9b1a1-bb51-4cde-80ea-a51bd14edb06.jpg)

**Comment by neo-cld** [comment]
After correct measurement, the distance between hole edge is 1.60 mm. The diameter of hole is 4.2 mm. The distance from hole edge to panel's front/back edge is 13.5-13.4 mm.  The distance from hole edge to panel's side edge is 12.8 mm. The correction should be done.

**Comment by kuoliangkwong** [comment]
Cool~ look forward to the new update =)
